---
- hosts: dev
  become: true
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
#        - create_repo
#        - install_packages
#        - firewall
#        - file_copy
#        - packages
#        - hosts
        - specs