---
- hosts: all
  become: true
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - create_repo
        - install_packages
        - firewall
        - file_copy
        - packages
        - hosts
        - specs
#        - issue
#        - cron_syslog
#        - target_mode
        - lvm_creation
